# Generated by Django 4.1 on 2024-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_column='Topic', max_length=45)),
                ('origin', models.CharField(db_column='Origin', max_length=45)),
                ('author', models.CharField(db_column='Author', max_length=45)),
                ('abstract', models.CharField(blank=True, db_column='Abstract', max_length=255, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comment', max_length=255, null=True)),
                ('url', models.CharField(blank=True, db_column='Url', max_length=255, null=True)),
            ],
            options={
                'db_table': 'spider_db',
                'managed': True,
            },
        ),
    ]
