# Generated by Django 4.1 on 2024-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spiderdb",
            name="negative",
            field=models.FloatField(blank=True, db_column="Negative", null=True),
        ),
        migrations.AddField(
            model_name="spiderdb",
            name="neutral",
            field=models.FloatField(blank=True, db_column="Neutral", null=True),
        ),
        migrations.AddField(
            model_name="spiderdb",
            name="positive",
            field=models.FloatField(blank=True, db_column="Positive", null=True),
        ),
    ]
